# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Eva Tool CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: npm install && npm run build && npm run docs:build
    - name: Generate GitHub Pages v3
      # You may pin to the exact commit or the version.
      # uses: peaceiris/actions-github-pages@b80a30e9bf3c1ec596532c3813f0aff094f555e2
      uses: peaceiris/actions-github-pages@v3.1.12
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./dist
        # Set Git user.name
        user_name: eva
        # Set Git user.email
        user_email: eva@zaozao.run
        # Set custom commit message
        commit_message: "ci: github action build"
        # Set tag name
        tag_name: ci
